In [1]:
# import summary
from torchsummary import summary
import segmentation_models_pytorch as smp
import torch
import torch.nn as nn

In [23]:
model_a = smp.Unet(encoder_weights = None, in_channels =10, classes = 5, add_reconstruction_head=True)
model_b = smp.Unet(encoder_weights = None, in_channels =10, classes = 5, add_reconstruction_head=True)
#model_a2 = smp.Unet(encoder_weights = None, in_channels =3, classes = 5 )

In [24]:
# sum of weights
temp_model = smp.Unet(encoder_weights = None, in_channels =10, classes = 5, add_reconstruction_head=False)

In [32]:
a = model_a.encoder.state_dict()
b = model_b.encoder.state_dict()
c = temp_model.encoder.state_dict()
for i in c:
    c[i] = (a[i] + b[i])/2

In [36]:
d= smp.Unet(encoder_weights = None, in_channels =10, classes = 5, add_reconstruction_head=False)
d.encoder.load_state_dict(c)

In [37]:
for i in d.encoder.parameters():
    print(i[0][0])
    break
for i in model_a.encoder.parameters():
    print(i[0][0])
    break
for i in model_b.encoder.parameters():
    print(i[0][0])
    break

tensor([[-2.5504e-03,  1.3099e-03, -9.0313e-03, -1.2774e-02, -1.6580e-02,
         -2.3181e-03, -2.1028e-02],
        [ 1.9606e-02, -1.6555e-03, -4.8861e-03,  3.7449e-02, -2.8395e-02,
          1.5006e-02, -3.0219e-02],
        [-9.2350e-03, -3.4425e-03, -1.9886e-02, -2.6173e-02,  6.9705e-03,
         -3.0422e-02,  8.1734e-03],
        [ 4.3664e-03, -2.4689e-02,  7.7594e-03,  3.6499e-05, -2.3412e-02,
          8.2842e-03,  1.2254e-02],
        [-2.0060e-02,  1.9321e-02, -2.3938e-02,  2.6235e-03, -5.6517e-03,
          2.9064e-02, -4.2669e-02],
        [ 1.3119e-02,  2.5382e-02, -2.7725e-02, -3.7611e-02, -6.9014e-03,
         -9.6965e-03, -1.6031e-03],
        [-3.3830e-03,  2.2193e-03, -1.2554e-02,  2.3453e-03, -2.0687e-02,
          1.4804e-02, -2.5015e-02]], grad_fn=<SelectBackward0>)
tensor([[ 0.0173, -0.0231, -0.0250,  0.0007,  0.0035, -0.0306, -0.0161],
        [-0.0001,  0.0231, -0.0273,  0.0375, -0.0317,  0.0016, -0.0200],
        [-0.0144,  0.0155, -0.0098, -0.0330,  0.0114, -0

In [3]:
for i in model_a.encoder.parameters():
    print(i[0][0])
    break

tensor([[-0.0010, -0.0243,  0.0213,  0.0437, -0.0288,  0.0357,  0.0054],
        [-0.0111,  0.0035,  0.0258, -0.0231, -0.0316,  0.0379,  0.0414],
        [ 0.0195, -0.0025,  0.0408,  0.0398, -0.0137, -0.0020, -0.0425],
        [ 0.0385,  0.0387,  0.0026, -0.0328, -0.0381, -0.0309,  0.0351],
        [-0.0183,  0.0185, -0.0439,  0.0391, -0.0397, -0.0308, -0.0062],
        [-0.0275, -0.0409, -0.0163,  0.0205, -0.0154, -0.0269,  0.0187],
        [-0.0065, -0.0433, -0.0325,  0.0419, -0.0087,  0.0232,  0.0261]],
       grad_fn=<SelectBackward0>)


In [4]:
for i in model_b.encoder.parameters():
    print(i[0][0])
    break

tensor([[-0.0164, -0.0293, -0.0260,  0.0436,  0.0218,  0.0094,  0.0306],
        [-0.0254, -0.0030, -0.0282,  0.0344,  0.0202,  0.0148,  0.0320],
        [ 0.0326,  0.0392,  0.0247,  0.0225, -0.0286, -0.0133,  0.0133],
        [ 0.0215, -0.0220,  0.0153, -0.0337, -0.0163,  0.0006, -0.0273],
        [ 0.0295,  0.0208, -0.0440,  0.0379, -0.0165,  0.0316,  0.0146],
        [ 0.0194,  0.0312, -0.0394,  0.0285,  0.0095,  0.0185, -0.0217],
        [ 0.0258,  0.0385, -0.0404,  0.0220, -0.0330,  0.0100, -0.0382]],
       grad_fn=<SelectBackward0>)


In [38]:
u = [1,2,3]
u.

AttributeError: 'list' object has no attribute 'item'

In [17]:
# create a new encoder for a new model_c with averaged weights from encoders of model_a and model_b
model_c = smp.Unet(encoder_weights = None, in_channels =10, classes = 5, add_reconstruction_head=False)

# averaging the weights of the encoders of model_a and model_b
for model_a_layer, model_b_layer, model_c_layer in zip(model_a.encoder.parameters(), model_b.encoder.parameters(), model_c.encoder.parameters()):
    model_c_layer.data = (model_a_layer.data + model_b_layer.data)/2
    print(model_c_layer.data)
# check if the weights of the encoders of model_a and model_b are the same as the weights of the encoder of model_c

tensor([[[[ 2.3335e-03, -1.6482e-02, -1.7181e-02,  ..., -2.1378e-02,
            2.0893e-02,  5.9854e-03],
          [ 2.1225e-02, -9.9324e-03, -1.8733e-02,  ...,  1.0441e-02,
            2.8230e-02,  1.5728e-03],
          [-3.8817e-03, -2.6315e-02, -1.4606e-02,  ..., -4.9458e-03,
            3.0368e-02, -1.7078e-03],
          ...,
          [ 2.2251e-02,  1.3740e-02, -1.1287e-03,  ...,  6.2923e-03,
           -1.5192e-02,  1.0463e-02],
          [ 2.3509e-02, -3.2039e-02,  2.2361e-02,  ...,  6.3201e-03,
           -2.0825e-02,  9.6442e-03],
          [ 6.4910e-03,  4.4815e-03,  2.4994e-02,  ..., -2.1047e-02,
            2.5221e-02,  1.9116e-02]],

         [[-4.1738e-03,  6.4233e-03, -1.9323e-02,  ...,  2.6062e-02,
            1.8908e-02, -2.3722e-02],
          [ 2.3607e-02, -1.5610e-02,  9.0338e-03,  ...,  3.6762e-03,
           -3.1159e-02, -1.1614e-02],
          [-2.3812e-02, -2.5580e-03,  8.5319e-03,  ..., -9.7923e-03,
            2.0319e-02, -2.1082e-02],
          ...,
     

In [16]:
for i in model_c.encoder.parameters():
    print(i[0][0])
    break

tensor([[ 0.0023, -0.0165, -0.0172,  0.0342, -0.0214,  0.0209,  0.0060],
        [ 0.0212, -0.0099, -0.0187,  0.0210,  0.0104,  0.0282,  0.0016],
        [-0.0039, -0.0263, -0.0146,  0.0101, -0.0049,  0.0304, -0.0017],
        [-0.0094,  0.0080, -0.0443, -0.0173, -0.0020,  0.0276,  0.0035],
        [ 0.0223,  0.0137, -0.0011, -0.0121,  0.0063, -0.0152,  0.0105],
        [ 0.0235, -0.0320,  0.0224, -0.0197,  0.0063, -0.0208,  0.0096],
        [ 0.0065,  0.0045,  0.0250,  0.0042, -0.0210,  0.0252,  0.0191]],
       grad_fn=<SelectBackward0>)


In [18]:
a = torch.Tensor([[ 0.0251, -0.0150, -0.0116,  0.0364, -0.0391, -0.0027,  0.0186],
        [ 0.0259, -0.0250, -0.0042,  0.0242,  0.0093,  0.0148, -0.0022],
        [ 0.0365, -0.0099, -0.0150, -0.0227, -0.0002,  0.0204, -0.0365],
        [-0.0409, -0.0146, -0.0444, -0.0312,  0.0359,  0.0117,  0.0295],
        [ 0.0222,  0.0112,  0.0295,  0.0008,  0.0047, -0.0027, -0.0031],
        [ 0.0400, -0.0193,  0.0157, -0.0313, -0.0235, -0.0131,  0.0133],
        [ 0.0112, -0.0011,  0.0055, -0.0235, -0.0360,  0.0263,  0.0115]])

b = torch.Tensor([[-0.0204, -0.0180, -0.0228,  0.0321, -0.0036,  0.0445, -0.0066],
        [ 0.0166,  0.0051, -0.0333,  0.0179,  0.0115,  0.0417,  0.0053],
        [-0.0442, -0.0428, -0.0142,  0.0429, -0.0097,  0.0403,  0.0331],
        [ 0.0221,  0.0307, -0.0441, -0.0034, -0.0399,  0.0435, -0.0224],
        [ 0.0223,  0.0163, -0.0318, -0.0250,  0.0078, -0.0277,  0.0240],
        [ 0.0071, -0.0447,  0.0291, -0.0081,  0.0361, -0.0286,  0.0060],
        [ 0.0018,  0.0100,  0.0444,  0.0320, -0.0061,  0.0242,  0.0267]])


In [19]:
c= (a+b)/2
print(c)

tensor([[ 0.0023, -0.0165, -0.0172,  0.0342, -0.0214,  0.0209,  0.0060],
        [ 0.0213, -0.0099, -0.0188,  0.0210,  0.0104,  0.0283,  0.0015],
        [-0.0038, -0.0264, -0.0146,  0.0101, -0.0049,  0.0303, -0.0017],
        [-0.0094,  0.0081, -0.0443, -0.0173, -0.0020,  0.0276,  0.0036],
        [ 0.0223,  0.0137, -0.0012, -0.0121,  0.0062, -0.0152,  0.0104],
        [ 0.0236, -0.0320,  0.0224, -0.0197,  0.0063, -0.0208,  0.0096],
        [ 0.0065,  0.0044,  0.0249,  0.0043, -0.0210,  0.0252,  0.0191]])


In [11]:
model_b = smp.Unet(encoder_weights = None, in_channels =10, classes = 5, add_reconstruction_head=False)

In [12]:
model_b.reconstruction_head

In [6]:
#test random data to see if model runs
tensor_x = torch.rand(2, 10, 512, 512)  # random tensor for 2 samples, 10 bands, 512x512
tensor_y = torch.randint(0, 5, (2, 512, 512))  # random tensor for 2 samples, 512x512

In [7]:
y_cap = model_b(tensor_x)

In [9]:
y_cap[0].shape, y_cap[1].shape

(torch.Size([2, 5, 512, 512]), torch.Size([2, 10, 512, 512]))

In [15]:
len(y_cap)

2

In [29]:
model_b.reconstruction_head

In [7]:
y_cap_ = model_b(tensor_x)
y_cap.shape

torch.Size([2, 5, 512, 512])

In [23]:
y_cap[1].shape, y_cap[0].shape

(torch.Size([2, 10, 512, 512]), torch.Size([2, 5, 512, 512]))

In [3]:
model_a.reconstruction_head

ReconstructionHead(
  (0): Conv2d(16, 10, kernel_size=(1, 1), stride=(1, 1))
  (1): Identity()
  (2): Sigmoid()
)

In [7]:
model_a.segmentation_head

SegmentationHead(
  (0): Conv2d(16, 5, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): Identity()
  (2): Activation(
    (activation): Identity()
  )
)

In [3]:
for i in model_a.encoder.parameters():
    print(i[0,0,:])
    break

tensor([[-0.0146,  0.0261, -0.0068,  0.0198,  0.0196, -0.0152,  0.0189],
        [ 0.0161,  0.0146,  0.0262, -0.0216, -0.0138,  0.0124,  0.0305],
        [ 0.0113, -0.0199,  0.0175,  0.0074,  0.0259,  0.0254, -0.0383],
        [-0.0574, -0.0429, -0.0048, -0.0193, -0.0183,  0.0395,  0.0245],
        [ 0.0320, -0.0243, -0.0101, -0.0244,  0.0069, -0.0445, -0.0272],
        [-0.0972,  0.0111,  0.0456, -0.0159,  0.0154,  0.0196, -0.0055],
        [ 0.0119,  0.0100,  0.0001,  0.0053, -0.0542, -0.0411,  0.0133]],
       grad_fn=<SliceBackward0>)


In [4]:
for i in model_a2.encoder.parameters():
    print(i[0,0,:])
    break

tensor([[ 0.0167,  0.0147,  0.0140, -0.0144,  0.0077, -0.0211, -0.0242],
        [ 0.0121,  0.0172, -0.0148, -0.0091, -0.0361,  0.0115, -0.0227],
        [-0.0149,  0.0214, -0.0236,  0.0010, -0.0016,  0.0342,  0.0167],
        [ 0.0040, -0.0174, -0.0271, -0.0479,  0.0022, -0.0087,  0.0322],
        [-0.0225, -0.0134,  0.0023,  0.0273,  0.0222,  0.0321, -0.0450],
        [ 0.0549,  0.0020, -0.0146, -0.0284, -0.0064,  0.0227, -0.0306],
        [ 0.0375, -0.0069,  0.0175,  0.0330,  0.0047, -0.0063, -0.0106]],
       grad_fn=<SliceBackward0>)


In [8]:
for i in model_a2.decoder.parameters():
    print(i[0,0,:])
    break

tensor([[ 0.0251,  0.0241, -0.0101],
        [ 0.0006,  0.0168,  0.0034],
        [ 0.0236, -0.0121, -0.0122]], grad_fn=<SliceBackward0>)


In [9]:
for i in model_a.decoder.parameters():
    print(i[0,0,:])
    break

tensor([[-0.0006, -0.0130,  0.0081],
        [ 0.0021,  0.0201, -0.0294],
        [-0.0211,  0.0055,  0.0057]], grad_fn=<SliceBackward0>)


In [12]:
#set encoder no grad
for param in model_a.encoder.parameters():
    param.requires_grad = False

for i,param in enumerate(model_a.parameters()):
    print(i,param.requires_grad)

0 False
1 False
2 False
3 False
4 False
5 False
6 False
7 False
8 False
9 False
10 False
11 False
12 False
13 False
14 False
15 False
16 False
17 False
18 False
19 False
20 False
21 False
22 False
23 False
24 False
25 False
26 False
27 False
28 False
29 False
30 False
31 False
32 False
33 False
34 False
35 False
36 False
37 False
38 False
39 False
40 False
41 False
42 False
43 False
44 False
45 False
46 False
47 False
48 False
49 False
50 False
51 False
52 False
53 False
54 False
55 False
56 False
57 False
58 False
59 False
60 False
61 False
62 False
63 False
64 False
65 False
66 False
67 False
68 False
69 False
70 False
71 False
72 False
73 False
74 False
75 False
76 False
77 False
78 False
79 False
80 False
81 False
82 False
83 False
84 False
85 False
86 False
87 False
88 False
89 False
90 False
91 False
92 False
93 False
94 False
95 False
96 False
97 False
98 False
99 False
100 False
101 False
102 False
103 False
104 False
105 False
106 False
107 False
108 True
109 True
110 True
111

In [6]:
model_a.encoder = model_a2.encoder

In [16]:
for i in model_a.encoder.parameters():
    print(i[0,0,:])
    break


tensor([[ 0.0076,  0.0254, -0.0206,  0.0027,  0.0125, -0.0284,  0.0264],
        [-0.0170, -0.0123,  0.0053, -0.0054, -0.0022, -0.0348,  0.0405],
        [ 0.0194,  0.0017,  0.0015,  0.0048,  0.0316, -0.0491,  0.0072],
        [ 0.0155, -0.0032,  0.0205, -0.0155, -0.0434,  0.0307,  0.0266],
        [ 0.0099,  0.0214, -0.0301,  0.0141, -0.0254, -0.0412,  0.0025],
        [ 0.0058,  0.0112,  0.0258,  0.0082,  0.0155, -0.0276,  0.0088],
        [-0.0188,  0.0008, -0.0379,  0.0572, -0.0082,  0.0056,  0.0285]])


In [15]:
# change final layer of model_a so that i can have a segmentation task output and an autoencoder output
model_a.segmentation_head

SegmentationHead(
  (0): Conv2d(16, 5, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): Identity()
  (2): Activation(
    (activation): Identity()
  )
)

In [23]:
model_b = UNet(n_channels=3, n_classes=11)

model_b2 = UNet(n_channels=3, n_classes=11)

In [24]:
# load model
ckpt = torch.load(r'E:\Thesis\outputs\43829_siam18\model_outputs\fold_0_best_model.pth', map_location=torch.device('cpu'))
model_b.load_state_dict(ckpt['model_state_dict'])

<All keys matched successfully>

In [51]:
# copy weights from pretrained model to new model for encoder
for name, param in model_b.named_parameters():
    if 'inc' in name or 'down' in name:
        print(name)
        model_b2.state_dict()[name].copy_(param)

inc.double_conv.0.weight
inc.double_conv.1.weight
inc.double_conv.1.bias
inc.double_conv.3.weight
inc.double_conv.4.weight
inc.double_conv.4.bias
down1.maxpool_conv.1.double_conv.0.weight
down1.maxpool_conv.1.double_conv.1.weight
down1.maxpool_conv.1.double_conv.1.bias
down1.maxpool_conv.1.double_conv.3.weight
down1.maxpool_conv.1.double_conv.4.weight
down1.maxpool_conv.1.double_conv.4.bias
down2.maxpool_conv.1.double_conv.0.weight
down2.maxpool_conv.1.double_conv.1.weight
down2.maxpool_conv.1.double_conv.1.bias
down2.maxpool_conv.1.double_conv.3.weight
down2.maxpool_conv.1.double_conv.4.weight
down2.maxpool_conv.1.double_conv.4.bias
down3.maxpool_conv.1.double_conv.0.weight
down3.maxpool_conv.1.double_conv.1.weight
down3.maxpool_conv.1.double_conv.1.bias
down3.maxpool_conv.1.double_conv.3.weight
down3.maxpool_conv.1.double_conv.4.weight
down3.maxpool_conv.1.double_conv.4.bias
down4.maxpool_conv.1.double_conv.0.weight
down4.maxpool_conv.1.double_conv.1.weight
down4.maxpool_conv.1.doubl

In [65]:
for i, (name, param) in enumerate(model_b.named_parameters()):
    if 'up'in name:
        print(name)
        print(param[0])
        print(model_b2.state_dict()[name][0])
        break

up1.up.weight
tensor([[[-2.3668e-02, -2.1197e-02],
         [-8.6756e-03,  1.8748e-02]],

        [[ 1.1258e-02, -3.7060e-03],
         [ 1.1938e-03, -6.7100e-06]],

        [[ 1.0943e-02, -9.9354e-03],
         [ 5.4060e-03, -4.2682e-03]],

        ...,

        [[-1.2293e-03, -1.0758e-02],
         [ 4.5752e-03, -5.3634e-03]],

        [[-1.2952e-02, -1.1074e-02],
         [-1.5103e-02,  8.2881e-03]],

        [[ 1.6445e-02,  6.3214e-03],
         [ 3.4183e-03, -2.1769e-02]]], grad_fn=<SelectBackward0>)
tensor([[[-0.0125, -0.0135],
         [ 0.0010, -0.0209]],

        [[ 0.0090,  0.0050],
         [-0.0072, -0.0152]],

        [[-0.0047, -0.0057],
         [ 0.0088, -0.0047]],

        ...,

        [[-0.0212, -0.0007],
         [-0.0101, -0.0091]],

        [[-0.0058,  0.0102],
         [ 0.0168, -0.0091]],

        [[ 0.0141,  0.0114],
         [ 0.0118,  0.0028]]])


In [66]:
# freeze encoder layers 
for name, param in model_b2.named_parameters():
    if 'inc' in name or 'down' in name:
        param.requires_grad = False

In [34]:
for i, (name, param) in enumerate(model_b.named_parameters()):
    print(i, name, param.shape)

0 inc.double_conv.0.weight torch.Size([64, 3, 3, 3])
1 inc.double_conv.1.weight torch.Size([64])
2 inc.double_conv.1.bias torch.Size([64])
3 inc.double_conv.3.weight torch.Size([64, 64, 3, 3])
4 inc.double_conv.4.weight torch.Size([64])
5 inc.double_conv.4.bias torch.Size([64])
6 down1.maxpool_conv.1.double_conv.0.weight torch.Size([128, 64, 3, 3])
7 down1.maxpool_conv.1.double_conv.1.weight torch.Size([128])
8 down1.maxpool_conv.1.double_conv.1.bias torch.Size([128])
9 down1.maxpool_conv.1.double_conv.3.weight torch.Size([128, 128, 3, 3])
10 down1.maxpool_conv.1.double_conv.4.weight torch.Size([128])
11 down1.maxpool_conv.1.double_conv.4.bias torch.Size([128])
12 down2.maxpool_conv.1.double_conv.0.weight torch.Size([256, 128, 3, 3])
13 down2.maxpool_conv.1.double_conv.1.weight torch.Size([256])
14 down2.maxpool_conv.1.double_conv.1.bias torch.Size([256])
15 down2.maxpool_conv.1.double_conv.3.weight torch.Size([256, 256, 3, 3])
16 down2.maxpool_conv.1.double_conv.4.weight torch.Size([2

In [25]:
#show all layer parameters of model_b
summary(model_b, (3, 256, 256))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 256, 256]           1,728
       BatchNorm2d-2         [-1, 64, 256, 256]             128
              ReLU-3         [-1, 64, 256, 256]               0
            Conv2d-4         [-1, 64, 256, 256]          36,864
       BatchNorm2d-5         [-1, 64, 256, 256]             128
              ReLU-6         [-1, 64, 256, 256]               0
        DoubleConv-7         [-1, 64, 256, 256]               0
         MaxPool2d-8         [-1, 64, 128, 128]               0
            Conv2d-9        [-1, 128, 128, 128]          73,728
      BatchNorm2d-10        [-1, 128, 128, 128]             256
             ReLU-11        [-1, 128, 128, 128]               0
           Conv2d-12        [-1, 128, 128, 128]         147,456
      BatchNorm2d-13        [-1, 128, 128, 128]             256
             ReLU-14        [-1, 128, 1

In [8]:
summary(model_a, (3, 256, 256))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 128, 128]           9,408
       BatchNorm2d-2         [-1, 64, 128, 128]             128
              ReLU-3         [-1, 64, 128, 128]               0
         MaxPool2d-4           [-1, 64, 64, 64]               0
            Conv2d-5           [-1, 64, 64, 64]          36,864
       BatchNorm2d-6           [-1, 64, 64, 64]             128
              ReLU-7           [-1, 64, 64, 64]               0
            Conv2d-8           [-1, 64, 64, 64]          36,864
       BatchNorm2d-9           [-1, 64, 64, 64]             128
             ReLU-10           [-1, 64, 64, 64]               0
       BasicBlock-11           [-1, 64, 64, 64]               0
           Conv2d-12           [-1, 64, 64, 64]          36,864
      BatchNorm2d-13           [-1, 64, 64, 64]             128
             ReLU-14           [-1, 64,

In [12]:
model_a.named_modules

<bound method Module.named_modules of Unet(
  (encoder): ResNetEncoder(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1

In [9]:
summary(model_b, (3, 256, 256))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 256, 256]           1,728
       BatchNorm2d-2         [-1, 64, 256, 256]             128
              ReLU-3         [-1, 64, 256, 256]               0
            Conv2d-4         [-1, 64, 256, 256]          36,864
       BatchNorm2d-5         [-1, 64, 256, 256]             128
              ReLU-6         [-1, 64, 256, 256]               0
        DoubleConv-7         [-1, 64, 256, 256]               0
         MaxPool2d-8         [-1, 64, 128, 128]               0
            Conv2d-9        [-1, 128, 128, 128]          73,728
      BatchNorm2d-10        [-1, 128, 128, 128]             256
             ReLU-11        [-1, 128, 128, 128]               0
           Conv2d-12        [-1, 128, 128, 128]         147,456
      BatchNorm2d-13        [-1, 128, 128, 128]             256
             ReLU-14        [-1, 128, 1

In [13]:
model_b.named_modules

<bound method Module.named_modules of UNet(
  (inc): DoubleConv(
    (double_conv): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU(inplace=True)
    )
  )
  (down1): Down(
    (maxpool_conv): Sequential(
      (0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (1): DoubleConv(
        (double_conv): Sequential(
          (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
          (3): Conv2d(128, 128, kernel_size=(3, 3), stride